### ISSUE TITLE
Render MATSim network tiles per region 

### ISSUE THREAD

**Issue by dhixsingh** [agentsoz/ees-ui#1]
Make sure that the correct MATSim network tiles are rendered based on the selected region in the map settings panel.  Swithcing regions should hide the current region tiles and load the selected region tiles.

See agentsoz/ees-server#1.

**Comment by ayoung012** [comment]
Loading matsim tiles for different regions as per changes made for agentsoz/ees-server#1.
Not yet hiding previously selected tiles

**Comment by ayoung012** [comment]
Hiding previously selected tiles see [commit](https://github.com/agentsoz/ees-ui/commit/58020a0f4b4890813decb1b365e9bd33a036fb18)

**Comment by dhixsingh** [comment]
@ayoung012, note that you can reference a commit directly by using the hash like this: 58020a0. GitHub is smart enough to realise it is a commit reference and automatically converts it to a link. Handy.
