### ISSUE TITLE
Add time slider for visualising the fire shape 

### ISSUE THREAD

**Issue by dhixsingh** [agentsoz/ees-ui#3]
Moving the slider back and forth should update the fire shape.

**Comment by dhixsingh** [comment]
The `HOUR_BURNT` attribute in the GeoJson gives the hour offset from the start of the fire, which is actually not encoded in the shapefile.

**Comment by dhixsingh** [comment]
Also see https://www.mapbox.com/mapbox-gl-js/example/timeline-animation/.

**Comment by ayoung012** [comment]
@dhixsingh See branch feature/fire-slider fire initial basic slider, note slow performance due to setFilter probably doing some pretty serious un-ordered float calcs on 'HOUR_BURNT' property. I am unable to find much information on sorting/indexing this property. Will experiment further during the week.

**Comment by dhixsingh** [comment]
I had a look and see what you mean @ayoung012.

One option is to offload some computing to the server. We could make every slider move request a new shape for the given time. The tradeoff will be that you have to contend with the communication / transfer lag. Judging by how long it takes to load the full shape now, this might not make it any faster though.  

Another option is that you apply all the filters (for each time slider step), upfront when you load the shape, and save each result in a new layer. All this will take a bit of time, but that is ok, we could show a "loading fire data" progress indicator. But then the slider updates should become fast, as all you would be doing is making the indexed layer visible. This also has the benefit that you calculate it once and save it, as compared to (re)calculating each time you move the slider.

**Comment by ayoung012** [comment]
@dhixsingh,

Offloading the computation to the server would benefit us, given how well it handles the MATSim tiles, but how it would perform with more than a few users dependent on the same server is another question...

I think caching is a good idea, and could even be done by the server. This would limit our slider steps to a specified arbitrary step size for all fires. Are steps to be limited to specific hour/minute intervals for any length fire, or a percentage of a fire length, eg 10% of a 12 hour fire is 0.12 hr step size?

**Comment by dhixsingh** [comment]
I think a fixed step size of `10 mins` would be sufficient. Make it easily configurable so that we can adjust it as we go without too much hassle. For starters see if layer caching on the client side will do the job, if not we can try and move some of that to the server.

**Comment by ayoung012** [comment]
@dhixsingh See above commit for initial exploration, we end up with about 500 layers. note that it doesn't seem to 'cache' the filters, still seems to calculate them upon becoming visible.

I will try breaking these up manually (programmatically upon selecting a fire) by timestep into seperate  geojson object 'sources', hopefully preventing it from struggling so much with scanning through single source to apply its fairly specific filters for each timestep layer. If the provided geojson is stored ordered by HOUR_BURNT, I can achieve this quite efficiently.

**Comment by dhixsingh** [comment]
Yes that doesn't seem to cache it at all, and is not workable. See how you go with breaking it up into separate sources.

**Comment by ayoung012** [comment]
@dhixsingh Performs very well when the geojson is preprocessed. Initial processing happens fairly quickly and rendering on slider input is very smooth.

**Comment by dhixsingh** [comment]
Just had a look. Very nice! Great if you could add time markers to the panel with offset in minutes, remove the `fire progression` heading (so make it a vertically thin slider) and move it to the bottom of the screen. We can then decide later where that should eventually fit in.

**Comment by ayoung012** [comment]
- [x] Set colour of cell based on fire intensity `E_INTSTY` 
https://stackoverflow.com/questions/40138463/setting-different-fill-colors-for-geojson-objects-in-google-maps-api
- [x] Activate slider if fire is visible
- [x] Slider labels responsive to screen size
- [x] Configurable fire opacity (map settings)
- [x] 3D fire height `FLAME_HT`
