### ISSUE TITLE
Add 3d height and intensity colours to fire shape

### ISSUE THREAD

**Issue by dhixsingh** [agentsoz/ees-ui#4]
See https://www.mapbox.com/mapbox-gl-js/example/3d-buildings/.

**Comment by dhixsingh** [comment]
@ayoung012 I will let you know which attributes to use to calculate the height of the fire.

**Comment by dhixsingh** [comment]
`flame_ht` and `e_intsty` are the columns you will need to pull the data out of.

**Comment by ayoung012** [comment]
@dhixsingh note black colour when intensity is null. Overall, a pretty neat effect...
https://blog.mapbox.com/data-driven-styling-for-fill-layers-in-mapbox-gl-js-80bb5292af4e

**Comment by dhixsingh** [comment]
:+1: Could you make the colour scheme/shades for the fire configurable too, as I am sure we will want to fiddle with it later. Coming along very nicely!

**Comment by dhixsingh** [comment]
@ayoung012 note that I cannot change the map base layer anymore, it is stuck on Dark. Would be great if you could spend some time on setting up testing this week too.

**Comment by dhixsingh** [comment]
The 3d height works well, nice! 

Though, I noticed some functionality gets messed up when I change the map base layer now from Dark to Satellite (probably others too). Mainly
* the fire is gone (hidden behind layers?)
* the road network seems to  disappear too
* changing regions does nothing after that (fly-to doesn't work).

**Comment by ayoung012** [comment]
@dhixsingh The above is now fixed and somewhat accounted for in some unit tests. Selenium tests to come...
3D has some noticable performance degradation on slower devices, I propose having 3D off by default and a dedicated button for enabling it.

**Comment by dhixsingh** [comment]
Yes agree re making the 3d effect optional.

**Comment by dhixsingh** [comment]
Could you also 

* add a `pitch` setting to the map init and set it to 60 degrees or something as a default, to make the 3D effect more obvious; and
* change the map's max zoom to allow zooming in further; at the moment with max zoom you can't get the names of some small streets.

**Comment by ayoung012** [comment]
@dhixsingh These have been done. Note that pitch is set upon selecting 3D mode in settings.
