### ISSUE TITLE
Allow disruptions/messaging to be attached to a network link 

### ISSUE THREAD

**Issue by dhixsingh** [agentsoz/ees-ui#6]
We want to be able to click on a MATSim network link and modify its attributes (shapefile attribute table properties). The idea is to be able to specify time based disruptions/ emergency messages. 

See https://github.com/agentsoz/bdi-abm-integration/issues/1#issuecomment-367548805 for the kind of data we want to attach to the link, where `startHHMM` will be picked up from the slider setting (#3) and the `impactedLinks` will just contain the selected link. The rest will be filled in using a popup box. 

Example of an emergency message is [here](https://github.com/agentsoz/ees/blob/master/scenarios/surf-coast-shire/torquay-3000/scenario_messages.json#L14-L23).

**Comment by ayoung012** [comment]
Workflow to be addressed with strategy from previous UI
